mod jvm;
mod native;
mod scripting;

use crate::{plugin::PluginLanguage, protocol::PROTOCOL_SCHEMA_SHA256, replica::lower_hex};

pub(super) struct GeneratedFile {
    pub(super) path: String,
    pub(super) contents: String,
}

#[derive(Clone, Copy)]
pub(super) struct Recipe {
    pub(super) language: &'static str,
    pub(super) checkout: &'static str,
    pub(super) dependencies: &'static [(&'static str, &'static str)],
    pub(super) steps: &'static [&'static [&'static str]],
    pub(super) runtime: &'static [&'static str],
    pub(super) gitignore: &'static str,
}

pub(super) fn render(
    language: PluginLanguage,
    plugin_id: &str,
    plugin_name: &str,
) -> Vec<GeneratedFile> {
    let (recipe, mut files) = match language {
        PluginLanguage::Dotnet => native::dotnet(),
        PluginLanguage::Cpp => native::cpp(),
        PluginLanguage::Go => native::go(),
        PluginLanguage::Java => jvm::java(),
        PluginLanguage::Kotlin => jvm::kotlin(),
        PluginLanguage::Scala => jvm::scala(),
        PluginLanguage::Clojure => jvm::clojure(),
        PluginLanguage::Javascript => scripting::javascript(),
        PluginLanguage::Typescript => scripting::typescript(),
        PluginLanguage::Python => scripting::python(),
        PluginLanguage::Rust => native::rust(),
        PluginLanguage::Swift => native::swift(),
        PluginLanguage::Elixir => scripting::elixir(),
        PluginLanguage::Haskell => native::haskell(),
    };
    files.push(file("oll.toml", manifest(&recipe, plugin_id, plugin_name)));
    files.push(file(".gitignore", format!("{}\n", recipe.gitignore.trim())));
    files.push(file(
        "README.md",
        format!(
            "# {plugin_name}\n\nA {language} onelastleaf plugin generated by `oll plugin new`.\n\nThe example `echo` action returns its arguments. Run the language's normal test command before installing the repository through `oll plugin install`.\n",
            language = recipe.language,
        ),
    ));
    for generated in &mut files {
        generated.path = generated
            .path
            .replace("__OLL_PLUGIN_NAME__", plugin_name)
            .replace("__OLL_PLUGIN_MODULE__", &plugin_name.replace('-', "_"));
        generated.contents = generated
            .contents
            .replace("__OLL_PLUGIN_ID__", plugin_id)
            .replace("__OLL_PLUGIN_NAME__", plugin_name)
            .replace("__OLL_PLUGIN_MODULE__", &plugin_name.replace('-', "_"));
    }
    files
}

pub(super) fn file(path: &'static str, contents: impl Into<String>) -> GeneratedFile {
    GeneratedFile {
        path: path.to_owned(),
        contents: contents.into(),
    }
}

fn manifest(recipe: &Recipe, plugin_id: &str, plugin_name: &str) -> String {
    let mut output = format!(
        "format_version = 1\n\n[plugin]\nid = \"{plugin_id}\"\nname = \"{plugin_name}\"\nprotocol_fingerprint = \"{}\"\n\n[source]\ncheckout = \"{}\"\n",
        lower_hex(&PROTOCOL_SCHEMA_SHA256),
        recipe.checkout,
    );
    for (executable, hint) in recipe.dependencies {
        output.push_str(&format!(
            "\n[[source.dependencies]]\nexecutable = \"{executable}\"\nhint = \"{hint}\"\n"
        ));
    }
    for step in recipe.steps {
        output.push_str("\n[[source.steps]]\nargv = [");
        push_toml_array(&mut output, step);
        output.push_str("]\n");
    }
    output.push_str("\n[runtime]\nargv = [");
    push_toml_array(&mut output, recipe.runtime);
    output.push_str("]\n");
    output
}

fn push_toml_array(output: &mut String, values: &[&str]) {
    for (index, value) in values.iter().enumerate() {
        if index != 0 {
            output.push_str(", ");
        }
        output.push('"');
        output.push_str(value);
        output.push('"');
    }
}
